# .goreleaser.yaml
version: 2
project_name: ash
before:
  hooks:
    - go mod tidy
builds:
  - id: ash
    main: ./
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    flags:
      - -trimpath
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: ash{{ if eq .Os "windows" }}.exe{{ end }}
archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README*
      - LICENSE*
      - docs/**/*
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
brews:
  - name: ash
    repository:
      owner: warmdev17
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/warmdev17/ash/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@warmdev17.com
    homepage: "https://github.com/warmdev17/ash"
    description: "Ash CLI tool for automated GitLab homework submission"
    license: "MIT"
    test: |
      system "#{bin}/ash --version"

checksum:
  name_template: "checksums.txt"
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  draft: true
  replace_existing_draft: true
