# .goreleaser.yaml
project_name: ash
before:
  hooks:
    - go mod tidy
builds:
  - id: ash
    main: ./
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    flags:
      - -trimpath
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
    binary: ash{{ if eq .Os "windows" }}.exe{{ end }}
archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README*
      - LICENSE*
      - docs/**/*
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
checksum:
  name_template: 'checksums.txt'
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  draft: true
  replace_existing_draft: true
